/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface ScopedConditional {
        "renderHello": boolean;
    }
}
declare global {
    interface HTMLScopedConditionalElement extends Components.ScopedConditional, HTMLStencilElement {
    }
    var HTMLScopedConditionalElement: {
        prototype: HTMLScopedConditionalElement;
        new (): HTMLScopedConditionalElement;
    };
    interface HTMLElementTagNameMap {
        "scoped-conditional": HTMLScopedConditionalElement;
    }
}
declare namespace LocalJSX {
    interface ScopedConditional {
        "renderHello"?: boolean;
    }
    interface IntrinsicElements {
        "scoped-conditional": ScopedConditional;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "scoped-conditional": LocalJSX.ScopedConditional & JSXBase.HTMLAttributes<HTMLScopedConditionalElement>;
        }
    }
}
